package com.moulberry.flashback.editor.ui;

import com.mojang.blaze3d.platform.InputConstants;
import imgui.moulberry90.flag.ImGuiKey;

/**
 * Maps Minecraft/SDL scancodes (see {@link InputConstants}) onto Dear ImGui's key enum.
 * These are physical positions, which is what SDL reports in keyboard events.
 */
public class ImGuiKeyMapping {

    public static int scancodeToImGuiKey(final int scancode) {
        switch (scancode) {
            case InputConstants.KEY_TAB:
                return ImGuiKey.Tab;
            case InputConstants.KEY_LEFT:
                return ImGuiKey.LeftArrow;
            case InputConstants.KEY_RIGHT:
                return ImGuiKey.RightArrow;
            case InputConstants.KEY_UP:
                return ImGuiKey.UpArrow;
            case InputConstants.KEY_DOWN:
                return ImGuiKey.DownArrow;
            case InputConstants.KEY_PAGEUP:
                return ImGuiKey.PageUp;
            case InputConstants.KEY_PAGEDOWN:
                return ImGuiKey.PageDown;
            case InputConstants.KEY_HOME:
                return ImGuiKey.Home;
            case InputConstants.KEY_END:
                return ImGuiKey.End;
            case InputConstants.KEY_INSERT:
                return ImGuiKey.Insert;
            case InputConstants.KEY_DELETE:
                return ImGuiKey.Delete;
            case InputConstants.KEY_BACKSPACE:
                return ImGuiKey.Backspace;
            case InputConstants.KEY_SPACE:
                return ImGuiKey.Space;
            case InputConstants.KEY_RETURN:
                return ImGuiKey.Enter;
            case InputConstants.KEY_ESCAPE:
                return ImGuiKey.Escape;
            case InputConstants.KEY_APOSTROPHE:
                return ImGuiKey.Apostrophe;
            case InputConstants.KEY_COMMA:
                return ImGuiKey.Comma;
            case InputConstants.KEY_MINUS:
                return ImGuiKey.Minus;
            case InputConstants.KEY_PERIOD:
                return ImGuiKey.Period;
            case InputConstants.KEY_SLASH:
                return ImGuiKey.Slash;
            case InputConstants.KEY_SEMICOLON:
                return ImGuiKey.Semicolon;
            case InputConstants.KEY_EQUALS:
                return ImGuiKey.Equal;
            case InputConstants.KEY_LBRACKET:
                return ImGuiKey.LeftBracket;
            case InputConstants.KEY_BACKSLASH:
                return ImGuiKey.Backslash;
            case InputConstants.KEY_RBRACKET:
                return ImGuiKey.RightBracket;
            case InputConstants.KEY_GRAVE:
                return ImGuiKey.GraveAccent;
            case InputConstants.KEY_CAPSLOCK:
                return ImGuiKey.CapsLock;
            case InputConstants.KEY_SCROLLLOCK:
                return ImGuiKey.ScrollLock;
            case InputConstants.KEY_NUMLOCK:
                return ImGuiKey.NumLock;
            case InputConstants.KEY_PRINTSCREEN:
                return ImGuiKey.PrintScreen;
            case InputConstants.KEY_PAUSE:
                return ImGuiKey.Pause;
            case InputConstants.KEY_NUMPAD0:
                return ImGuiKey.Keypad0;
            case InputConstants.KEY_NUMPAD1:
                return ImGuiKey.Keypad1;
            case InputConstants.KEY_NUMPAD2:
                return ImGuiKey.Keypad2;
            case InputConstants.KEY_NUMPAD3:
                return ImGuiKey.Keypad3;
            case InputConstants.KEY_NUMPAD4:
                return ImGuiKey.Keypad4;
            case InputConstants.KEY_NUMPAD5:
                return ImGuiKey.Keypad5;
            case InputConstants.KEY_NUMPAD6:
                return ImGuiKey.Keypad6;
            case InputConstants.KEY_NUMPAD7:
                return ImGuiKey.Keypad7;
            case InputConstants.KEY_NUMPAD8:
                return ImGuiKey.Keypad8;
            case InputConstants.KEY_NUMPAD9:
                return ImGuiKey.Keypad9;
            case InputConstants.KEY_NUMPADCOMMA:
                return ImGuiKey.KeypadDecimal;
            case 84:
                return ImGuiKey.KeypadDivide;
            case InputConstants.KEY_MULTIPLY:
                return ImGuiKey.KeypadMultiply;
            case 86:
                return ImGuiKey.KeypadSubtract;
            case InputConstants.KEY_ADD:
                return ImGuiKey.KeypadAdd;
            case InputConstants.KEY_NUMPADENTER:
                return ImGuiKey.KeypadEnter;
            case InputConstants.KEY_NUMPADEQUALS:
                return ImGuiKey.KeypadEqual;
            case InputConstants.KEY_LSHIFT:
                return ImGuiKey.LeftShift;
            case InputConstants.KEY_LCONTROL:
                return ImGuiKey.LeftCtrl;
            case InputConstants.KEY_LALT:
                return ImGuiKey.LeftAlt;
            case InputConstants.KEY_LGUI:
                return ImGuiKey.LeftSuper;
            case InputConstants.KEY_RSHIFT:
                return ImGuiKey.RightShift;
            case InputConstants.KEY_RCONTROL:
                return ImGuiKey.RightCtrl;
            case InputConstants.KEY_RALT:
                return ImGuiKey.RightAlt;
            case InputConstants.KEY_RGUI:
                return ImGuiKey.RightSuper;
            case 118:
                return ImGuiKey.Menu;
            case InputConstants.KEY_0:
                return ImGuiKey._0;
            case InputConstants.KEY_1:
                return ImGuiKey._1;
            case InputConstants.KEY_2:
                return ImGuiKey._2;
            case InputConstants.KEY_3:
                return ImGuiKey._3;
            case InputConstants.KEY_4:
                return ImGuiKey._4;
            case InputConstants.KEY_5:
                return ImGuiKey._5;
            case InputConstants.KEY_6:
                return ImGuiKey._6;
            case InputConstants.KEY_7:
                return ImGuiKey._7;
            case InputConstants.KEY_8:
                return ImGuiKey._8;
            case InputConstants.KEY_9:
                return ImGuiKey._9;
            case InputConstants.KEY_A:
                return ImGuiKey.A;
            case InputConstants.KEY_B:
                return ImGuiKey.B;
            case InputConstants.KEY_C:
                return ImGuiKey.C;
            case InputConstants.KEY_D:
                return ImGuiKey.D;
            case InputConstants.KEY_E:
                return ImGuiKey.E;
            case InputConstants.KEY_F:
                return ImGuiKey.F;
            case InputConstants.KEY_G:
                return ImGuiKey.G;
            case InputConstants.KEY_H:
                return ImGuiKey.H;
            case InputConstants.KEY_I:
                return ImGuiKey.I;
            case InputConstants.KEY_J:
                return ImGuiKey.J;
            case InputConstants.KEY_K:
                return ImGuiKey.K;
            case InputConstants.KEY_L:
                return ImGuiKey.L;
            case InputConstants.KEY_M:
                return ImGuiKey.M;
            case InputConstants.KEY_N:
                return ImGuiKey.N;
            case InputConstants.KEY_O:
                return ImGuiKey.O;
            case InputConstants.KEY_P:
                return ImGuiKey.P;
            case InputConstants.KEY_Q:
                return ImGuiKey.Q;
            case InputConstants.KEY_R:
                return ImGuiKey.R;
            case InputConstants.KEY_S:
                return ImGuiKey.S;
            case InputConstants.KEY_T:
                return ImGuiKey.T;
            case InputConstants.KEY_U:
                return ImGuiKey.U;
            case InputConstants.KEY_V:
                return ImGuiKey.V;
            case InputConstants.KEY_W:
                return ImGuiKey.W;
            case InputConstants.KEY_X:
                return ImGuiKey.X;
            case InputConstants.KEY_Y:
                return ImGuiKey.Y;
            case InputConstants.KEY_Z:
                return ImGuiKey.Z;
            case InputConstants.KEY_F1:
                return ImGuiKey.F1;
            case InputConstants.KEY_F2:
                return ImGuiKey.F2;
            case InputConstants.KEY_F3:
                return ImGuiKey.F3;
            case InputConstants.KEY_F4:
                return ImGuiKey.F4;
            case InputConstants.KEY_F5:
                return ImGuiKey.F5;
            case InputConstants.KEY_F6:
                return ImGuiKey.F6;
            case InputConstants.KEY_F7:
                return ImGuiKey.F7;
            case InputConstants.KEY_F8:
                return ImGuiKey.F8;
            case InputConstants.KEY_F9:
                return ImGuiKey.F9;
            case InputConstants.KEY_F10:
                return ImGuiKey.F10;
            case InputConstants.KEY_F11:
                return ImGuiKey.F11;
            case InputConstants.KEY_F12:
                return ImGuiKey.F12;
            case InputConstants.KEY_F13:
                return ImGuiKey.F13;
            case InputConstants.KEY_F14:
                return ImGuiKey.F14;
            case InputConstants.KEY_F15:
                return ImGuiKey.F15;
            case InputConstants.KEY_F16:
                return ImGuiKey.F16;
            case InputConstants.KEY_F17:
                return ImGuiKey.F17;
            case InputConstants.KEY_F18:
                return ImGuiKey.F18;
            case InputConstants.KEY_F19:
                return ImGuiKey.F19;
            case InputConstants.KEY_F20:
                return ImGuiKey.F20;
            case InputConstants.KEY_F21:
                return ImGuiKey.F21;
            case InputConstants.KEY_F22:
                return ImGuiKey.F22;
            case InputConstants.KEY_F23:
                return ImGuiKey.F23;
            case InputConstants.KEY_F24:
                return ImGuiKey.F24;
            default:
                return ImGuiKey.None;
        }
    }

}
