package com.moulberry.flashback.editor.keybinds;

import java.util.Locale;

import static org.lwjgl.glfw.GLFW.*;

public class KeybindHelper {

    public static String glfwToConfig(int glfw) {
        return switch (glfw) {
            default -> "none";
            case Keybind.FAKE_SCROLL_KEY -> "scroll";
            case -GLFW_MOUSE_BUTTON_LEFT-1 -> "mouseleft";
            case -GLFW_MOUSE_BUTTON_MIDDLE-1 -> "mousemiddle";
            case -GLFW_MOUSE_BUTTON_RIGHT-1 -> "mouseright";
            case -GLFW_MOUSE_BUTTON_4-1 -> "mouse4";
            case -GLFW_MOUSE_BUTTON_5-1 -> "mouse5";
            case -GLFW_MOUSE_BUTTON_6-1 -> "mouse6";
            case -GLFW_MOUSE_BUTTON_7-1 -> "mouse7";
            case -GLFW_MOUSE_BUTTON_8-1 -> "mouse8";
            case GLFW_KEY_SPACE         -> "space";
            case GLFW_KEY_APOSTROPHE    -> "apostrophe";
            case GLFW_KEY_COMMA         -> "comma";
            case GLFW_KEY_MINUS         -> "minus";
            case GLFW_KEY_PERIOD        -> "period";
            case GLFW_KEY_SLASH         -> "slash";
            case GLFW_KEY_0             -> "0";
            case GLFW_KEY_1             -> "1";
            case GLFW_KEY_2             -> "2";
            case GLFW_KEY_3             -> "3";
            case GLFW_KEY_4             -> "4";
            case GLFW_KEY_5             -> "5";
            case GLFW_KEY_6             -> "6";
            case GLFW_KEY_7             -> "7";
            case GLFW_KEY_8             -> "8";
            case GLFW_KEY_9             -> "9";
            case GLFW_KEY_SEMICOLON     -> "semicolon";
            case GLFW_KEY_EQUAL         -> "equal";
            case GLFW_KEY_A             -> "a";
            case GLFW_KEY_B             -> "b";
            case GLFW_KEY_C             -> "c";
            case GLFW_KEY_D             -> "d";
            case GLFW_KEY_E             -> "e";
            case GLFW_KEY_F             -> "f";
            case GLFW_KEY_G             -> "g";
            case GLFW_KEY_H             -> "h";
            case GLFW_KEY_I             -> "i";
            case GLFW_KEY_J             -> "j";
            case GLFW_KEY_K             -> "k";
            case GLFW_KEY_L             -> "l";
            case GLFW_KEY_M             -> "m";
            case GLFW_KEY_N             -> "n";
            case GLFW_KEY_O             -> "o";
            case GLFW_KEY_P             -> "p";
            case GLFW_KEY_Q             -> "q";
            case GLFW_KEY_R             -> "r";
            case GLFW_KEY_S             -> "s";
            case GLFW_KEY_T             -> "t";
            case GLFW_KEY_U             -> "u";
            case GLFW_KEY_V             -> "v";
            case GLFW_KEY_W             -> "w";
            case GLFW_KEY_X             -> "x";
            case GLFW_KEY_Y             -> "y";
            case GLFW_KEY_Z             -> "z";
            case GLFW_KEY_LEFT_BRACKET  -> "leftbracket";
            case GLFW_KEY_BACKSLASH     -> "backslash";
            case GLFW_KEY_RIGHT_BRACKET -> "rightbracket";
            case GLFW_KEY_GRAVE_ACCENT  -> "graveaccent";
            case GLFW_KEY_WORLD_1       -> "world1";
            case GLFW_KEY_WORLD_2       -> "world2";
            case GLFW_KEY_ESCAPE        -> "escape";
            case GLFW_KEY_ENTER         -> "enter";
            case GLFW_KEY_TAB           -> "tab";
            case GLFW_KEY_BACKSPACE     -> "backspace";
            case GLFW_KEY_INSERT        -> "insert";
            case GLFW_KEY_DELETE        -> "delete";
            case GLFW_KEY_RIGHT         -> "right";
            case GLFW_KEY_LEFT          -> "left";
            case GLFW_KEY_DOWN          -> "down";
            case GLFW_KEY_UP            -> "up";
            case GLFW_KEY_PAGE_UP       -> "pageup";
            case GLFW_KEY_PAGE_DOWN     -> "pagedown";
            case GLFW_KEY_HOME          -> "home";
            case GLFW_KEY_END           -> "end";
            case GLFW_KEY_CAPS_LOCK     -> "capslock";
            case GLFW_KEY_SCROLL_LOCK   -> "scrolllock";
            case GLFW_KEY_NUM_LOCK      -> "numlock";
            case GLFW_KEY_PRINT_SCREEN  -> "printscreen";
            case GLFW_KEY_PAUSE         -> "pause";
            case GLFW_KEY_F1            -> "f1";
            case GLFW_KEY_F2            -> "f2";
            case GLFW_KEY_F3            -> "f3";
            case GLFW_KEY_F4            -> "f4";
            case GLFW_KEY_F5            -> "f5";
            case GLFW_KEY_F6            -> "f6";
            case GLFW_KEY_F7            -> "f7";
            case GLFW_KEY_F8            -> "f8";
            case GLFW_KEY_F9            -> "f9";
            case GLFW_KEY_F10           -> "f10";
            case GLFW_KEY_F11           -> "f11";
            case GLFW_KEY_F12           -> "f12";
            case GLFW_KEY_F13           -> "f13";
            case GLFW_KEY_F14           -> "f14";
            case GLFW_KEY_F15           -> "f15";
            case GLFW_KEY_F16           -> "f16";
            case GLFW_KEY_F17           -> "f17";
            case GLFW_KEY_F18           -> "f18";
            case GLFW_KEY_F19           -> "f19";
            case GLFW_KEY_F20           -> "f20";
            case GLFW_KEY_F21           -> "f21";
            case GLFW_KEY_F22           -> "f22";
            case GLFW_KEY_F23           -> "f23";
            case GLFW_KEY_F24           -> "f24";
            case GLFW_KEY_F25           -> "f25";
            case GLFW_KEY_KP_0          -> "kp0";
            case GLFW_KEY_KP_1          -> "kp1";
            case GLFW_KEY_KP_2          -> "kp2";
            case GLFW_KEY_KP_3          -> "kp3";
            case GLFW_KEY_KP_4          -> "kp4";
            case GLFW_KEY_KP_5          -> "kp5";
            case GLFW_KEY_KP_6          -> "kp6";
            case GLFW_KEY_KP_7          -> "kp7";
            case GLFW_KEY_KP_8          -> "kp8";
            case GLFW_KEY_KP_9          -> "kp9";
            case GLFW_KEY_KP_DECIMAL    -> "kpdecimal";
            case GLFW_KEY_KP_DIVIDE     -> "kpdivide";
            case GLFW_KEY_KP_MULTIPLY   -> "kpmultiply";
            case GLFW_KEY_KP_SUBTRACT   -> "kpsubtract";
            case GLFW_KEY_KP_ADD        -> "kpadd";
            case GLFW_KEY_KP_ENTER      -> "kpenter";
            case GLFW_KEY_KP_EQUAL      -> "kpequal";
            case GLFW_KEY_LEFT_SHIFT    -> "leftshift";
            case GLFW_KEY_LEFT_CONTROL  -> "leftcontrol";
            case GLFW_KEY_LEFT_ALT      -> "leftalt";
            case GLFW_KEY_LEFT_SUPER    -> "leftsuper";
            case GLFW_KEY_RIGHT_SHIFT   -> "rightshift";
            case GLFW_KEY_RIGHT_CONTROL -> "rightcontrol";
            case GLFW_KEY_RIGHT_ALT     -> "rightalt";
            case GLFW_KEY_RIGHT_SUPER   -> "rightsuper";
            case GLFW_KEY_MENU          -> "menu";
        };
    }

    public static int configToGlfw(String config) {
        return switch (config.toLowerCase(Locale.ROOT).replace("_", "")) {
            default -> 0;
            case "mouseleft"     -> -GLFW_MOUSE_BUTTON_LEFT-1;
            case "mousemiddle"   -> -GLFW_MOUSE_BUTTON_MIDDLE-1;
            case "mouseright"    -> -GLFW_MOUSE_BUTTON_RIGHT-1;
            case "mouse4"        -> -GLFW_MOUSE_BUTTON_4-1;
            case "mouse5"        -> -GLFW_MOUSE_BUTTON_5-1;
            case "mouse6"        -> -GLFW_MOUSE_BUTTON_6-1;
            case "mouse7"        -> -GLFW_MOUSE_BUTTON_7-1;
            case "mouse8"        -> -GLFW_MOUSE_BUTTON_8-1;
            case "scroll"        -> Keybind.FAKE_SCROLL_KEY;
            case "space"         -> GLFW_KEY_SPACE;
            case "apostrophe"    -> GLFW_KEY_APOSTROPHE;
            case "comma"         -> GLFW_KEY_COMMA;
            case "minus"         -> GLFW_KEY_MINUS;
            case "period"        -> GLFW_KEY_PERIOD;
            case "slash"         -> GLFW_KEY_SLASH;
            case "0"             -> GLFW_KEY_0;
            case "1"             -> GLFW_KEY_1;
            case "2"             -> GLFW_KEY_2;
            case "3"             -> GLFW_KEY_3;
            case "4"             -> GLFW_KEY_4;
            case "5"             -> GLFW_KEY_5;
            case "6"             -> GLFW_KEY_6;
            case "7"             -> GLFW_KEY_7;
            case "8"             -> GLFW_KEY_8;
            case "9"             -> GLFW_KEY_9;
            case "semicolon"     -> GLFW_KEY_SEMICOLON;
            case "equal"         -> GLFW_KEY_EQUAL;
            case "a"             -> GLFW_KEY_A;
            case "b"             -> GLFW_KEY_B;
            case "c"             -> GLFW_KEY_C;
            case "d"             -> GLFW_KEY_D;
            case "e"             -> GLFW_KEY_E;
            case "f"             -> GLFW_KEY_F;
            case "g"             -> GLFW_KEY_G;
            case "h"             -> GLFW_KEY_H;
            case "i"             -> GLFW_KEY_I;
            case "j"             -> GLFW_KEY_J;
            case "k"             -> GLFW_KEY_K;
            case "l"             -> GLFW_KEY_L;
            case "m"             -> GLFW_KEY_M;
            case "n"             -> GLFW_KEY_N;
            case "o"             -> GLFW_KEY_O;
            case "p"             -> GLFW_KEY_P;
            case "q"             -> GLFW_KEY_Q;
            case "r"             -> GLFW_KEY_R;
            case "s"             -> GLFW_KEY_S;
            case "t"             -> GLFW_KEY_T;
            case "u"             -> GLFW_KEY_U;
            case "v"             -> GLFW_KEY_V;
            case "w"             -> GLFW_KEY_W;
            case "x"             -> GLFW_KEY_X;
            case "y"             -> GLFW_KEY_Y;
            case "z"             -> GLFW_KEY_Z;
            case "leftbracket"   -> GLFW_KEY_LEFT_BRACKET;
            case "backslash"     -> GLFW_KEY_BACKSLASH;
            case "rightbracket"  -> GLFW_KEY_RIGHT_BRACKET;
            case "graveaccent"   -> GLFW_KEY_GRAVE_ACCENT;
            case "world1"        -> GLFW_KEY_WORLD_1;
            case "world2"        -> GLFW_KEY_WORLD_2;
            case "escape"        -> GLFW_KEY_ESCAPE;
            case "enter"         -> GLFW_KEY_ENTER;
            case "tab"           -> GLFW_KEY_TAB;
            case "backspace"     -> GLFW_KEY_BACKSPACE;
            case "insert"        -> GLFW_KEY_INSERT;
            case "delete"        -> GLFW_KEY_DELETE;
            case "right"         -> GLFW_KEY_RIGHT;
            case "left"          -> GLFW_KEY_LEFT;
            case "down"          -> GLFW_KEY_DOWN;
            case "up"            -> GLFW_KEY_UP;
            case "pageup"        -> GLFW_KEY_PAGE_UP;
            case "pagedown"      -> GLFW_KEY_PAGE_DOWN;
            case "home"          -> GLFW_KEY_HOME;
            case "end"           -> GLFW_KEY_END;
            case "capslock"      -> GLFW_KEY_CAPS_LOCK;
            case "scrolllock"    -> GLFW_KEY_SCROLL_LOCK;
            case "numlock"       -> GLFW_KEY_NUM_LOCK;
            case "printscreen"   -> GLFW_KEY_PRINT_SCREEN;
            case "pause"         -> GLFW_KEY_PAUSE;
            case "f1"            -> GLFW_KEY_F1;
            case "f2"            -> GLFW_KEY_F2;
            case "f3"            -> GLFW_KEY_F3;
            case "f4"            -> GLFW_KEY_F4;
            case "f5"            -> GLFW_KEY_F5;
            case "f6"            -> GLFW_KEY_F6;
            case "f7"            -> GLFW_KEY_F7;
            case "f8"            -> GLFW_KEY_F8;
            case "f9"            -> GLFW_KEY_F9;
            case "f10"           -> GLFW_KEY_F10;
            case "f11"           -> GLFW_KEY_F11;
            case "f12"           -> GLFW_KEY_F12;
            case "f13"           -> GLFW_KEY_F13;
            case "f14"           -> GLFW_KEY_F14;
            case "f15"           -> GLFW_KEY_F15;
            case "f16"           -> GLFW_KEY_F16;
            case "f17"           -> GLFW_KEY_F17;
            case "f18"           -> GLFW_KEY_F18;
            case "f19"           -> GLFW_KEY_F19;
            case "f20"           -> GLFW_KEY_F20;
            case "f21"           -> GLFW_KEY_F21;
            case "f22"           -> GLFW_KEY_F22;
            case "f23"           -> GLFW_KEY_F23;
            case "f24"           -> GLFW_KEY_F24;
            case "f25"           -> GLFW_KEY_F25;
            case "kp0", "num0", "numpad0", "keypad0"           -> GLFW_KEY_KP_0;
            case "kp1", "num1", "numpad1", "keypad1"           -> GLFW_KEY_KP_1;
            case "kp2", "num2", "numpad2", "keypad2"           -> GLFW_KEY_KP_2;
            case "kp3", "num3", "numpad3", "keypad3"           -> GLFW_KEY_KP_3;
            case "kp4", "num4", "numpad4", "keypad4"           -> GLFW_KEY_KP_4;
            case "kp5", "num5", "numpad5", "keypad5"           -> GLFW_KEY_KP_5;
            case "kp6", "num6", "numpad6", "keypad6"           -> GLFW_KEY_KP_6;
            case "kp7", "num7", "numpad7", "keypad7"           -> GLFW_KEY_KP_7;
            case "kp8", "num8", "numpad8", "keypad8"           -> GLFW_KEY_KP_8;
            case "kp9", "num9", "numpad9", "keypad9"           -> GLFW_KEY_KP_9;
            case "kpdecimal"     -> GLFW_KEY_KP_DECIMAL;
            case "kpdivide"      -> GLFW_KEY_KP_DIVIDE;
            case "kpmultiply"    -> GLFW_KEY_KP_MULTIPLY;
            case "kpsubtract"    -> GLFW_KEY_KP_SUBTRACT;
            case "kpadd"         -> GLFW_KEY_KP_ADD;
            case "kpenter"       -> GLFW_KEY_KP_ENTER;
            case "kpequal"       -> GLFW_KEY_KP_EQUAL;
            case "leftshift"     -> GLFW_KEY_LEFT_SHIFT;
            case "leftcontrol"   -> GLFW_KEY_LEFT_CONTROL;
            case "leftalt"       -> GLFW_KEY_LEFT_ALT;
            case "leftsuper"     -> GLFW_KEY_LEFT_SUPER;
            case "rightshift"    -> GLFW_KEY_RIGHT_SHIFT;
            case "rightcontrol"  -> GLFW_KEY_RIGHT_CONTROL;
            case "rightalt"      -> GLFW_KEY_RIGHT_ALT;
            case "rightsuper"    -> GLFW_KEY_RIGHT_SUPER;
            case "menu"          -> GLFW_KEY_MENU;
        };
    }

}
