package com.moulberry.flashback.editor.keybinds;

import java.util.Locale;

import com.mojang.blaze3d.platform.InputConstants;

public class KeybindHelper {

    public static String keyToConfig(int key) {
        return switch (key) {
            default -> "none";
            case Keybind.FAKE_SCROLL_KEY -> "scroll";
            case -0 - 1 -> "mouseleft";
            case -1 - 1 -> "mousemiddle";
            case -2 - 1 -> "mouseright";
            case -3 - 1 -> "mouse4";
            case -4 - 1 -> "mouse5";
            case -5 - 1 -> "mouse6";
            case -6 - 1 -> "mouse7";
            case -7 - 1 -> "mouse8";
            case InputConstants.KEY_SPACE         -> "space";
            case InputConstants.KEY_APOSTROPHE    -> "apostrophe";
            case InputConstants.KEY_COMMA         -> "comma";
            case InputConstants.KEY_MINUS         -> "minus";
            case InputConstants.KEY_PERIOD        -> "period";
            case InputConstants.KEY_SLASH         -> "slash";
            case InputConstants.KEY_0             -> "0";
            case InputConstants.KEY_1             -> "1";
            case InputConstants.KEY_2             -> "2";
            case InputConstants.KEY_3             -> "3";
            case InputConstants.KEY_4             -> "4";
            case InputConstants.KEY_5             -> "5";
            case InputConstants.KEY_6             -> "6";
            case InputConstants.KEY_7             -> "7";
            case InputConstants.KEY_8             -> "8";
            case InputConstants.KEY_9             -> "9";
            case InputConstants.KEY_SEMICOLON     -> "semicolon";
            case InputConstants.KEY_EQUALS         -> "equal";
            case InputConstants.KEY_A             -> "a";
            case InputConstants.KEY_B             -> "b";
            case InputConstants.KEY_C             -> "c";
            case InputConstants.KEY_D             -> "d";
            case InputConstants.KEY_E             -> "e";
            case InputConstants.KEY_F             -> "f";
            case InputConstants.KEY_G             -> "g";
            case InputConstants.KEY_H             -> "h";
            case InputConstants.KEY_I             -> "i";
            case InputConstants.KEY_J             -> "j";
            case InputConstants.KEY_K             -> "k";
            case InputConstants.KEY_L             -> "l";
            case InputConstants.KEY_M             -> "m";
            case InputConstants.KEY_N             -> "n";
            case InputConstants.KEY_O             -> "o";
            case InputConstants.KEY_P             -> "p";
            case InputConstants.KEY_Q             -> "q";
            case InputConstants.KEY_R             -> "r";
            case InputConstants.KEY_S             -> "s";
            case InputConstants.KEY_T             -> "t";
            case InputConstants.KEY_U             -> "u";
            case InputConstants.KEY_V             -> "v";
            case InputConstants.KEY_W             -> "w";
            case InputConstants.KEY_X             -> "x";
            case InputConstants.KEY_Y             -> "y";
            case InputConstants.KEY_Z             -> "z";
            case InputConstants.KEY_LBRACKET  -> "leftbracket";
            case InputConstants.KEY_BACKSLASH     -> "backslash";
            case InputConstants.KEY_RBRACKET -> "rightbracket";
            case InputConstants.KEY_GRAVE  -> "graveaccent";
            case 50       -> "world1";
            case 100       -> "world2";
            case InputConstants.KEY_ESCAPE        -> "escape";
            case InputConstants.KEY_RETURN         -> "enter";
            case InputConstants.KEY_TAB           -> "tab";
            case InputConstants.KEY_BACKSPACE     -> "backspace";
            case InputConstants.KEY_INSERT        -> "insert";
            case InputConstants.KEY_DELETE        -> "delete";
            case InputConstants.KEY_RIGHT         -> "right";
            case InputConstants.KEY_LEFT          -> "left";
            case InputConstants.KEY_DOWN          -> "down";
            case InputConstants.KEY_UP            -> "up";
            case InputConstants.KEY_PAGEUP       -> "pageup";
            case InputConstants.KEY_PAGEDOWN     -> "pagedown";
            case InputConstants.KEY_HOME          -> "home";
            case InputConstants.KEY_END           -> "end";
            case InputConstants.KEY_CAPSLOCK     -> "capslock";
            case InputConstants.KEY_SCROLLLOCK   -> "scrolllock";
            case InputConstants.KEY_NUMLOCK      -> "numlock";
            case InputConstants.KEY_PRINTSCREEN  -> "printscreen";
            case InputConstants.KEY_PAUSE         -> "pause";
            case InputConstants.KEY_F1            -> "f1";
            case InputConstants.KEY_F2            -> "f2";
            case InputConstants.KEY_F3            -> "f3";
            case InputConstants.KEY_F4            -> "f4";
            case InputConstants.KEY_F5            -> "f5";
            case InputConstants.KEY_F6            -> "f6";
            case InputConstants.KEY_F7            -> "f7";
            case InputConstants.KEY_F8            -> "f8";
            case InputConstants.KEY_F9            -> "f9";
            case InputConstants.KEY_F10           -> "f10";
            case InputConstants.KEY_F11           -> "f11";
            case InputConstants.KEY_F12           -> "f12";
            case InputConstants.KEY_F13           -> "f13";
            case InputConstants.KEY_F14           -> "f14";
            case InputConstants.KEY_F15           -> "f15";
            case InputConstants.KEY_F16           -> "f16";
            case InputConstants.KEY_F17           -> "f17";
            case InputConstants.KEY_F18           -> "f18";
            case InputConstants.KEY_F19           -> "f19";
            case InputConstants.KEY_F20           -> "f20";
            case InputConstants.KEY_F21           -> "f21";
            case InputConstants.KEY_F22           -> "f22";
            case InputConstants.KEY_F23           -> "f23";
            case InputConstants.KEY_F24           -> "f24";
            case InputConstants.KEY_NUMPAD0          -> "kp0";
            case InputConstants.KEY_NUMPAD1          -> "kp1";
            case InputConstants.KEY_NUMPAD2          -> "kp2";
            case InputConstants.KEY_NUMPAD3          -> "kp3";
            case InputConstants.KEY_NUMPAD4          -> "kp4";
            case InputConstants.KEY_NUMPAD5          -> "kp5";
            case InputConstants.KEY_NUMPAD6          -> "kp6";
            case InputConstants.KEY_NUMPAD7          -> "kp7";
            case InputConstants.KEY_NUMPAD8          -> "kp8";
            case InputConstants.KEY_NUMPAD9          -> "kp9";
            case InputConstants.KEY_NUMPADCOMMA    -> "kpdecimal";
            case 84     -> "kpdivide";
            case InputConstants.KEY_MULTIPLY   -> "kpmultiply";
            case 86   -> "kpsubtract";
            case InputConstants.KEY_ADD        -> "kpadd";
            case InputConstants.KEY_NUMPADENTER      -> "kpenter";
            case InputConstants.KEY_NUMPADEQUALS      -> "kpequal";
            case InputConstants.KEY_LSHIFT    -> "leftshift";
            case InputConstants.KEY_LCONTROL  -> "leftcontrol";
            case InputConstants.KEY_LALT      -> "leftalt";
            case InputConstants.KEY_LGUI    -> "leftsuper";
            case InputConstants.KEY_RSHIFT   -> "rightshift";
            case InputConstants.KEY_RCONTROL -> "rightcontrol";
            case InputConstants.KEY_RALT     -> "rightalt";
            case InputConstants.KEY_RGUI   -> "rightsuper";
            case 118          -> "menu";
        };
    }

    public static int configToKey(String config) {
        return switch (config.toLowerCase(Locale.ROOT).replace("_", "")) {
            default -> 0;
            case "mouseleft"     -> -0 - 1;
            case "mousemiddle"   -> -1 - 1;
            case "mouseright"    -> -2 - 1;
            case "mouse4"        -> -3 - 1;
            case "mouse5"        -> -4 - 1;
            case "mouse6"        -> -5 - 1;
            case "mouse7"        -> -6 - 1;
            case "mouse8"        -> -7 - 1;
            case "scroll"        -> Keybind.FAKE_SCROLL_KEY;
            case "space"         -> InputConstants.KEY_SPACE;
            case "apostrophe"    -> InputConstants.KEY_APOSTROPHE;
            case "comma"         -> InputConstants.KEY_COMMA;
            case "minus"         -> InputConstants.KEY_MINUS;
            case "period"        -> InputConstants.KEY_PERIOD;
            case "slash"         -> InputConstants.KEY_SLASH;
            case "0"             -> InputConstants.KEY_0;
            case "1"             -> InputConstants.KEY_1;
            case "2"             -> InputConstants.KEY_2;
            case "3"             -> InputConstants.KEY_3;
            case "4"             -> InputConstants.KEY_4;
            case "5"             -> InputConstants.KEY_5;
            case "6"             -> InputConstants.KEY_6;
            case "7"             -> InputConstants.KEY_7;
            case "8"             -> InputConstants.KEY_8;
            case "9"             -> InputConstants.KEY_9;
            case "semicolon"     -> InputConstants.KEY_SEMICOLON;
            case "equal"         -> InputConstants.KEY_EQUALS;
            case "a"             -> InputConstants.KEY_A;
            case "b"             -> InputConstants.KEY_B;
            case "c"             -> InputConstants.KEY_C;
            case "d"             -> InputConstants.KEY_D;
            case "e"             -> InputConstants.KEY_E;
            case "f"             -> InputConstants.KEY_F;
            case "g"             -> InputConstants.KEY_G;
            case "h"             -> InputConstants.KEY_H;
            case "i"             -> InputConstants.KEY_I;
            case "j"             -> InputConstants.KEY_J;
            case "k"             -> InputConstants.KEY_K;
            case "l"             -> InputConstants.KEY_L;
            case "m"             -> InputConstants.KEY_M;
            case "n"             -> InputConstants.KEY_N;
            case "o"             -> InputConstants.KEY_O;
            case "p"             -> InputConstants.KEY_P;
            case "q"             -> InputConstants.KEY_Q;
            case "r"             -> InputConstants.KEY_R;
            case "s"             -> InputConstants.KEY_S;
            case "t"             -> InputConstants.KEY_T;
            case "u"             -> InputConstants.KEY_U;
            case "v"             -> InputConstants.KEY_V;
            case "w"             -> InputConstants.KEY_W;
            case "x"             -> InputConstants.KEY_X;
            case "y"             -> InputConstants.KEY_Y;
            case "z"             -> InputConstants.KEY_Z;
            case "leftbracket"   -> InputConstants.KEY_LBRACKET;
            case "backslash"     -> InputConstants.KEY_BACKSLASH;
            case "rightbracket"  -> InputConstants.KEY_RBRACKET;
            case "graveaccent"   -> InputConstants.KEY_GRAVE;
            case "escape"        -> InputConstants.KEY_ESCAPE;
            case "enter"         -> InputConstants.KEY_RETURN;
            case "tab"           -> InputConstants.KEY_TAB;
            case "backspace"     -> InputConstants.KEY_BACKSPACE;
            case "insert"        -> InputConstants.KEY_INSERT;
            case "delete"        -> InputConstants.KEY_DELETE;
            case "right"         -> InputConstants.KEY_RIGHT;
            case "left"          -> InputConstants.KEY_LEFT;
            case "down"          -> InputConstants.KEY_DOWN;
            case "up"            -> InputConstants.KEY_UP;
            case "pageup"        -> InputConstants.KEY_PAGEUP;
            case "pagedown"      -> InputConstants.KEY_PAGEDOWN;
            case "home"          -> InputConstants.KEY_HOME;
            case "end"           -> InputConstants.KEY_END;
            case "capslock"      -> InputConstants.KEY_CAPSLOCK;
            case "scrolllock"    -> InputConstants.KEY_SCROLLLOCK;
            case "numlock"       -> InputConstants.KEY_NUMLOCK;
            case "printscreen"   -> InputConstants.KEY_PRINTSCREEN;
            case "pause"         -> InputConstants.KEY_PAUSE;
            case "f1"            -> InputConstants.KEY_F1;
            case "f2"            -> InputConstants.KEY_F2;
            case "f3"            -> InputConstants.KEY_F3;
            case "f4"            -> InputConstants.KEY_F4;
            case "f5"            -> InputConstants.KEY_F5;
            case "f6"            -> InputConstants.KEY_F6;
            case "f7"            -> InputConstants.KEY_F7;
            case "f8"            -> InputConstants.KEY_F8;
            case "f9"            -> InputConstants.KEY_F9;
            case "f10"           -> InputConstants.KEY_F10;
            case "f11"           -> InputConstants.KEY_F11;
            case "f12"           -> InputConstants.KEY_F12;
            case "f13"           -> InputConstants.KEY_F13;
            case "f14"           -> InputConstants.KEY_F14;
            case "f15"           -> InputConstants.KEY_F15;
            case "f16"           -> InputConstants.KEY_F16;
            case "f17"           -> InputConstants.KEY_F17;
            case "f18"           -> InputConstants.KEY_F18;
            case "f19"           -> InputConstants.KEY_F19;
            case "f20"           -> InputConstants.KEY_F20;
            case "f21"           -> InputConstants.KEY_F21;
            case "f22"           -> InputConstants.KEY_F22;
            case "f23"           -> InputConstants.KEY_F23;
            case "f24"           -> InputConstants.KEY_F24;
            case "kp0", "num0", "numpad0", "keypad0"           -> InputConstants.KEY_NUMPAD0;
            case "kp1", "num1", "numpad1", "keypad1"           -> InputConstants.KEY_NUMPAD1;
            case "kp2", "num2", "numpad2", "keypad2"           -> InputConstants.KEY_NUMPAD2;
            case "kp3", "num3", "numpad3", "keypad3"           -> InputConstants.KEY_NUMPAD3;
            case "kp4", "num4", "numpad4", "keypad4"           -> InputConstants.KEY_NUMPAD4;
            case "kp5", "num5", "numpad5", "keypad5"           -> InputConstants.KEY_NUMPAD5;
            case "kp6", "num6", "numpad6", "keypad6"           -> InputConstants.KEY_NUMPAD6;
            case "kp7", "num7", "numpad7", "keypad7"           -> InputConstants.KEY_NUMPAD7;
            case "kp8", "num8", "numpad8", "keypad8"           -> InputConstants.KEY_NUMPAD8;
            case "kp9", "num9", "numpad9", "keypad9"           -> InputConstants.KEY_NUMPAD9;
            case "kpdecimal"     -> InputConstants.KEY_NUMPADCOMMA;
            case "kpdivide"      -> 84;
            case "kpmultiply"    -> InputConstants.KEY_MULTIPLY;
            case "kpsubtract"    -> 86;
            case "kpadd"         -> InputConstants.KEY_ADD;
            case "kpenter"       -> InputConstants.KEY_NUMPADENTER;
            case "kpequal"       -> InputConstants.KEY_NUMPADEQUALS;
            case "leftshift"     -> InputConstants.KEY_LSHIFT;
            case "leftcontrol"   -> InputConstants.KEY_LCONTROL;
            case "leftalt"       -> InputConstants.KEY_LALT;
            case "leftsuper"     -> InputConstants.KEY_LGUI;
            case "rightshift"    -> InputConstants.KEY_RSHIFT;
            case "rightcontrol"  -> InputConstants.KEY_RCONTROL;
            case "rightalt"      -> InputConstants.KEY_RALT;
            case "rightsuper"    -> InputConstants.KEY_RGUI;
            case "menu"          -> 118;
        };
    }

}
