package com.moulberry.flashback.editor.keybinds;

import imgui.moulberry90.flag.ImGuiKey;
import imgui.moulberry90.flag.ImGuiMouseButton;

import java.util.Locale;

public class KeybindHelper {

    public static String imguiToConfig(int imgui) {
        return switch (imgui) {
            case -ImGuiMouseButton.Left-1 -> "mouseleft";
            case -ImGuiMouseButton.Middle-1 -> "mousemiddle";
            case -ImGuiMouseButton.Right-1 -> "mouseright";
            case -3-1 -> "mouse4";
            case -4-1 -> "mouse5";
            case ImGuiKey.Space          -> "space";
            case ImGuiKey.Apostrophe     -> "apostrophe";
            case ImGuiKey.Comma          -> "comma";
            case ImGuiKey.Minus          -> "minus";
            case ImGuiKey.Period         -> "period";
            case ImGuiKey.Slash          -> "slash";
            case ImGuiKey._0             -> "0";
            case ImGuiKey._1             -> "1";
            case ImGuiKey._2             -> "2";
            case ImGuiKey._3             -> "3";
            case ImGuiKey._4             -> "4";
            case ImGuiKey._5             -> "5";
            case ImGuiKey._6             -> "6";
            case ImGuiKey._7             -> "7";
            case ImGuiKey._8             -> "8";
            case ImGuiKey._9             -> "9";
            case ImGuiKey.Semicolon      -> "semicolon";
            case ImGuiKey.Equal          -> "equal";
            case ImGuiKey.A              -> "a";
            case ImGuiKey.B              -> "b";
            case ImGuiKey.C              -> "c";
            case ImGuiKey.D              -> "d";
            case ImGuiKey.E              -> "e";
            case ImGuiKey.F              -> "f";
            case ImGuiKey.G              -> "g";
            case ImGuiKey.H              -> "h";
            case ImGuiKey.I              -> "i";
            case ImGuiKey.J              -> "j";
            case ImGuiKey.K              -> "k";
            case ImGuiKey.L              -> "l";
            case ImGuiKey.M              -> "m";
            case ImGuiKey.N              -> "n";
            case ImGuiKey.O              -> "o";
            case ImGuiKey.P              -> "p";
            case ImGuiKey.Q              -> "q";
            case ImGuiKey.R              -> "r";
            case ImGuiKey.S              -> "s";
            case ImGuiKey.T              -> "t";
            case ImGuiKey.U              -> "u";
            case ImGuiKey.V              -> "v";
            case ImGuiKey.W              -> "w";
            case ImGuiKey.X              -> "x";
            case ImGuiKey.Y              -> "y";
            case ImGuiKey.Z              -> "z";
            case ImGuiKey.LeftBracket    -> "leftbracket";
            case ImGuiKey.Backslash      -> "backslash";
            case ImGuiKey.RightBracket   -> "rightbracket";
            case ImGuiKey.GraveAccent    -> "graveaccent";
            case ImGuiKey.Escape         -> "escape";
            case ImGuiKey.Enter          -> "enter";
            case ImGuiKey.Tab            -> "tab";
            case ImGuiKey.Backspace      -> "backspace";
            case ImGuiKey.Insert         -> "insert";
            case ImGuiKey.Delete         -> "delete";
            case ImGuiKey.RightArrow     -> "right";
            case ImGuiKey.LeftArrow      -> "left";
            case ImGuiKey.DownArrow      -> "down";
            case ImGuiKey.UpArrow        -> "up";
            case ImGuiKey.PageUp         -> "pageup";
            case ImGuiKey.PageDown       -> "pagedown";
            case ImGuiKey.Home           -> "home";
            case ImGuiKey.End            -> "end";
            case ImGuiKey.CapsLock       -> "capslock";
            case ImGuiKey.ScrollLock     -> "scrolllock";
            case ImGuiKey.NumLock        -> "numlock";
            case ImGuiKey.PrintScreen    -> "printscreen";
            case ImGuiKey.Pause          -> "pause";
            case ImGuiKey.F1             -> "f1";
            case ImGuiKey.F2             -> "f2";
            case ImGuiKey.F3             -> "f3";
            case ImGuiKey.F4             -> "f4";
            case ImGuiKey.F5             -> "f5";
            case ImGuiKey.F6             -> "f6";
            case ImGuiKey.F7             -> "f7";
            case ImGuiKey.F8             -> "f8";
            case ImGuiKey.F9             -> "f9";
            case ImGuiKey.F10            -> "f10";
            case ImGuiKey.F11            -> "f11";
            case ImGuiKey.F12            -> "f12";
            case ImGuiKey.F13            -> "f13";
            case ImGuiKey.F14            -> "f14";
            case ImGuiKey.F15            -> "f15";
            case ImGuiKey.F16            -> "f16";
            case ImGuiKey.F17            -> "f17";
            case ImGuiKey.F18            -> "f18";
            case ImGuiKey.F19            -> "f19";
            case ImGuiKey.F20            -> "f20";
            case ImGuiKey.F21            -> "f21";
            case ImGuiKey.F22            -> "f22";
            case ImGuiKey.F23            -> "f23";
            case ImGuiKey.F24            -> "f24";
            case ImGuiKey.Keypad0        -> "kp0";
            case ImGuiKey.Keypad1        -> "kp1";
            case ImGuiKey.Keypad2        -> "kp2";
            case ImGuiKey.Keypad3        -> "kp3";
            case ImGuiKey.Keypad4        -> "kp4";
            case ImGuiKey.Keypad5        -> "kp5";
            case ImGuiKey.Keypad6        -> "kp6";
            case ImGuiKey.Keypad7        -> "kp7";
            case ImGuiKey.Keypad8        -> "kp8";
            case ImGuiKey.Keypad9        -> "kp9";
            case ImGuiKey.KeypadDecimal  -> "kpdecimal";
            case ImGuiKey.KeypadDivide   -> "kpdivide";
            case ImGuiKey.KeypadMultiply -> "kpmultiply";
            case ImGuiKey.KeypadSubtract -> "kpsubtract";
            case ImGuiKey.KeypadAdd      -> "kpadd";
            case ImGuiKey.KeypadEnter    -> "kpenter";
            case ImGuiKey.KeypadEqual    -> "kpequal";
            case ImGuiKey.LeftShift      -> "leftshift";
            case ImGuiKey.LeftCtrl       -> "leftcontrol";
            case ImGuiKey.LeftAlt        -> "leftalt";
            case ImGuiKey.LeftSuper      -> "leftsuper";
            case ImGuiKey.RightShift     -> "rightshift";
            case ImGuiKey.RightCtrl      -> "rightcontrol";
            case ImGuiKey.RightAlt       -> "rightalt";
            case ImGuiKey.RightSuper     -> "rightsuper";
            case ImGuiKey.Menu           -> "menu";
            default -> "none";
        };
    }

    public static int configToImgui(String config) {
        return switch (config.toLowerCase(Locale.ROOT).replace("_", "").trim()) {
            case "mouseleft", "mouse1" -> -ImGuiMouseButton.Left-1;
            case "mousemiddle", "mouse2" -> -ImGuiMouseButton.Middle-1;
            case "mouseright", "mouse3" -> -ImGuiMouseButton.Right-1;
            case "mouse4" -> -3-1;
            case "mouse5" -> -4-1;
            case "space" -> ImGuiKey.Space;
            case "apostrophe" -> ImGuiKey.Apostrophe;
            case "comma" -> ImGuiKey.Comma;
            case "minus" -> ImGuiKey.Minus;
            case "period" -> ImGuiKey.Period;
            case "slash" -> ImGuiKey.Slash;
            case "0" -> ImGuiKey._0;
            case "1" -> ImGuiKey._1;
            case "2" -> ImGuiKey._2;
            case "3" -> ImGuiKey._3;
            case "4" -> ImGuiKey._4;
            case "5" -> ImGuiKey._5;
            case "6" -> ImGuiKey._6;
            case "7" -> ImGuiKey._7;
            case "8" -> ImGuiKey._8;
            case "9" -> ImGuiKey._9;
            case "semicolon" -> ImGuiKey.Semicolon;
            case "equal" -> ImGuiKey.Equal;
            case "a" -> ImGuiKey.A;
            case "b" -> ImGuiKey.B;
            case "c" -> ImGuiKey.C;
            case "d" -> ImGuiKey.D;
            case "e" -> ImGuiKey.E;
            case "f" -> ImGuiKey.F;
            case "g" -> ImGuiKey.G;
            case "h" -> ImGuiKey.H;
            case "i" -> ImGuiKey.I;
            case "j" -> ImGuiKey.J;
            case "k" -> ImGuiKey.K;
            case "l" -> ImGuiKey.L;
            case "m" -> ImGuiKey.M;
            case "n" -> ImGuiKey.N;
            case "o" -> ImGuiKey.O;
            case "p" -> ImGuiKey.P;
            case "q" -> ImGuiKey.Q;
            case "r" -> ImGuiKey.R;
            case "s" -> ImGuiKey.S;
            case "t" -> ImGuiKey.T;
            case "u" -> ImGuiKey.U;
            case "v" -> ImGuiKey.V;
            case "w" -> ImGuiKey.W;
            case "x" -> ImGuiKey.X;
            case "y" -> ImGuiKey.Y;
            case "z" -> ImGuiKey.Z;
            case "leftbracket" -> ImGuiKey.LeftBracket;
            case "backslash" -> ImGuiKey.Backslash;
            case "rightbracket" -> ImGuiKey.RightBracket;
            case "graveaccent" -> ImGuiKey.GraveAccent;
            case "escape" -> ImGuiKey.Escape;
            case "enter" -> ImGuiKey.Enter;
            case "tab" -> ImGuiKey.Tab;
            case "backspace" -> ImGuiKey.Backspace;
            case "insert" -> ImGuiKey.Insert;
            case "delete" -> ImGuiKey.Delete;
            case "right" -> ImGuiKey.RightArrow;
            case "left" -> ImGuiKey.LeftArrow;
            case "down" -> ImGuiKey.DownArrow;
            case "up" -> ImGuiKey.UpArrow;
            case "pageup" -> ImGuiKey.PageUp;
            case "pagedown" -> ImGuiKey.PageDown;
            case "home" -> ImGuiKey.Home;
            case "end" -> ImGuiKey.End;
            case "capslock" -> ImGuiKey.CapsLock;
            case "scrolllock" -> ImGuiKey.ScrollLock;
            case "numlock" -> ImGuiKey.NumLock;
            case "printscreen" -> ImGuiKey.PrintScreen;
            case "pause" -> ImGuiKey.Pause;
            case "f1" -> ImGuiKey.F1;
            case "f2" -> ImGuiKey.F2;
            case "f3" -> ImGuiKey.F3;
            case "f4" -> ImGuiKey.F4;
            case "f5" -> ImGuiKey.F5;
            case "f6" -> ImGuiKey.F6;
            case "f7" -> ImGuiKey.F7;
            case "f8" -> ImGuiKey.F8;
            case "f9" -> ImGuiKey.F9;
            case "f10" -> ImGuiKey.F10;
            case "f11" -> ImGuiKey.F11;
            case "f12" -> ImGuiKey.F12;
            case "f13" -> ImGuiKey.F13;
            case "f14" -> ImGuiKey.F14;
            case "f15" -> ImGuiKey.F15;
            case "f16" -> ImGuiKey.F16;
            case "f17" -> ImGuiKey.F17;
            case "f18" -> ImGuiKey.F18;
            case "f19" -> ImGuiKey.F19;
            case "f20" -> ImGuiKey.F20;
            case "f21" -> ImGuiKey.F21;
            case "f22" -> ImGuiKey.F22;
            case "f23" -> ImGuiKey.F23;
            case "f24" -> ImGuiKey.F24;
            case "kp0", "num0", "numpad0", "keypad0" -> ImGuiKey.Keypad0;
            case "kp1", "num1", "numpad1", "keypad1" -> ImGuiKey.Keypad1;
            case "kp2", "num2", "numpad2", "keypad2" -> ImGuiKey.Keypad2;
            case "kp3", "num3", "numpad3", "keypad3" -> ImGuiKey.Keypad3;
            case "kp4", "num4", "numpad4", "keypad4" -> ImGuiKey.Keypad4;
            case "kp5", "num5", "numpad5", "keypad5" -> ImGuiKey.Keypad5;
            case "kp6", "num6", "numpad6", "keypad6" -> ImGuiKey.Keypad6;
            case "kp7", "num7", "numpad7", "keypad7" -> ImGuiKey.Keypad7;
            case "kp8", "num8", "numpad8", "keypad8" -> ImGuiKey.Keypad8;
            case "kp9", "num9", "numpad9", "keypad9" -> ImGuiKey.Keypad9;
            case "kpdecimal" -> ImGuiKey.KeypadDecimal;
            case "kpdivide" -> ImGuiKey.KeypadDivide;
            case "kpmultiply" -> ImGuiKey.KeypadMultiply;
            case "kpsubtract" -> ImGuiKey.KeypadSubtract;
            case "kpadd" -> ImGuiKey.KeypadAdd;
            case "kpenter" -> ImGuiKey.KeypadEnter;
            case "kpequal" -> ImGuiKey.KeypadEqual;
            case "leftshift" -> ImGuiKey.LeftShift;
            case "leftcontrol" -> ImGuiKey.LeftCtrl;
            case "leftalt" -> ImGuiKey.LeftAlt;
            case "leftsuper" -> ImGuiKey.LeftSuper;
            case "rightshift" -> ImGuiKey.RightShift;
            case "rightcontrol" -> ImGuiKey.RightCtrl;
            case "rightalt" -> ImGuiKey.RightAlt;
            case "rightsuper" -> ImGuiKey.RightSuper;
            case "menu" -> ImGuiKey.Menu;
            default -> 0;
        };
    }

}
